##### Copyright 2019 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [2]:
#@title MIT License
#
# Copyright (c) 2017 François Chollet
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# Text classification with TensorFlow Hub: Movie reviews

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/keras/text_classification_with_hub"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/text_classification_with_hub.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/text_classification_with_hub.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/keras/text_classification_with_hub.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This notebook classifies movie reviews as *positive* or *negative* using the text of the review. This is an example of *binary*—or two-class—classification, an important and widely applicable kind of machine learning problem.

The tutorial demonstrates the basic application of transfer learning with TensorFlow Hub and Keras.

We'll use the [IMDB dataset](https://www.tensorflow.org/api_docs/python/tf/keras/datasets/imdb) that contains the text of 50,000 movie reviews from the [Internet Movie Database](https://www.imdb.com/). These are split into 25,000 reviews for training and 25,000 reviews for testing. The training and testing sets are *balanced*, meaning they contain an equal number of positive and negative reviews. 

This notebook uses [tf.keras](https://www.tensorflow.org/guide/keras), a high-level API to build and train models in TensorFlow, and [TensorFlow Hub](https://www.tensorflow.org/hub), a library and platform for transfer learning. For a more advanced text classification tutorial using `tf.keras`, see the [MLCC Text Classification Guide](https://developers.google.com/machine-learning/guides/text-classification/).

In [3]:
!pip3 install -q tensorflow-hub
!pip3 install -q tensorflow-datasets

In [4]:
import numpy as np

import tensorflow as tf


import tensorflow_hub as hub
import tensorflow_datasets as tfds

print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.experimental.list_physical_devices("GPU") else "NOT AVAILABLE")

Version:  2.3.0
Eager mode:  True
Hub version:  0.9.0
GPU is NOT AVAILABLE


## Download the IMDB dataset

The IMDB dataset is available on [imdb reviews](https://www.tensorflow.org/datasets/catalog/imdb_reviews) or on [TensorFlow datasets](https://www.tensorflow.org/datasets). The following code downloads the IMDB dataset to your machine (or the colab runtime):

In [5]:
# Split the training set into 60% and 40%, so we'll end up with 15,000 examples
# for training, 10,000 examples for validation and 25,000 examples for testing.
train_data, validation_data, test_data = tfds.load(
    name="imdb_reviews", 
    split=('train[:60%]', 'train[60%:]', 'test'),
    as_supervised=True)

## Explore the data 

Let's take a moment to understand the format of the data. Each example is a sentence representing the movie review and a corresponding label. The sentence is not preprocessed in any way. The label is an integer value of either 0 or 1, where 0 is a negative review, and 1 is a positive review.

Let's print first 10 examples.

In [6]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))
train_examples_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

Let's also print the first 10 labels.

In [7]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

## Build the model

The neural network is created by stacking layers—this requires three main architectural decisions:

* How to represent the text?
* How many layers to use in the model?
* How many *hidden units* to use for each layer?

In this example, the input data consists of sentences. The labels to predict are either 0 or 1.

One way to represent the text is to convert sentences into embeddings vectors. We can use a pre-trained text embedding as the first layer, which will have three advantages:

*   we don't have to worry about text preprocessing,
*   we can benefit from transfer learning,
*   the embedding has a fixed size, so it's simpler to process.

For this example we will use a **pre-trained text embedding model** from [TensorFlow Hub](https://www.tensorflow.org/hub) called [google/tf2-preview/gnews-swivel-20dim/1](https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1).

There are three other pre-trained models to test for the sake of this tutorial:

* [google/tf2-preview/gnews-swivel-20dim-with-oov/1](https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim-with-oov/1) - same as [google/tf2-preview/gnews-swivel-20dim/1](https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1), but with 2.5% vocabulary converted to OOV buckets. This can help if vocabulary of the task and vocabulary of the model don't fully overlap.
* [google/tf2-preview/nnlm-en-dim50/1](https://tfhub.dev/google/tf2-preview/nnlm-en-dim50/1) - A much larger model with ~1M vocabulary size and 50 dimensions.
* [google/tf2-preview/nnlm-en-dim128/1](https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1) - Even larger model with ~1M vocabulary size and 128 dimensions.

Let's first create a Keras layer that uses a TensorFlow Hub model to embed the sentences, and try it out on a couple of input examples. Note that no matter the length of the input text, the output shape of the embeddings is: `(num_examples, embedding_dimension)`.

In [8]:
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)
hub_layer(train_examples_batch[:3])

<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ],
       [ 0.71152234, -0.6353217 ,  1.7385626 , -1.1168286 , -0.5451594 ,
        -1.1808156 ,  0.09504455,  1.4653089 ,  0.66059524,  0.79308075,
        -2.2268345 ,  0.07446612, -1.4075904 , -0.70645386, -1.907037  ,
         1.4419787 ,  1.9551861 , -0.42660055, -2.8022065 ,  0.43727064]],
      dtype=float32)>

Let's now build the full model:

In [9]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense (Dense)                (None, 16)                336       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


The layers are stacked sequentially to build the classifier:

1. The first layer is a TensorFlow Hub layer. This layer uses a pre-trained Saved Model to map a sentence into its embedding vector. The pre-trained text embedding model that we are using ([google/tf2-preview/gnews-swivel-20dim/1](https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1)) splits the sentence into tokens, embeds each token and then combines the embedding. The resulting dimensions are: `(num_examples, embedding_dimension)`.
2. This fixed-length output vector is piped through a fully-connected (`Dense`) layer with 16 hidden units.
3. The last layer is densely connected with a single output node.

Let's compile the model.

### Loss function and optimizer

A model needs a loss function and an optimizer for training. Since this is a binary classification problem and the model outputs logits (a single-unit layer with a linear activation), we'll use the `binary_crossentropy` loss function.

This isn't the only choice for a loss function, you could, for instance, choose `mean_squared_error`. But, generally, `binary_crossentropy` is better for dealing with probabilities—it measures the "distance" between probability distributions, or in our case, between the ground-truth distribution and the predictions.

Later, when we are exploring regression problems (say, to predict the price of a house), we will see how to use another loss function called mean squared error.

Now, configure the model to use an optimizer and a loss function:

In [10]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

## Train the model

Train the model for 20 epochs in mini-batches of 512 samples. This is 20 iterations over all samples in the `x_train` and `y_train` tensors. While training, monitor the model's loss and accuracy on the 10,000 samples from the validation set:

In [11]:
history = model.fit(train_data.shuffle(10000).batch(512),
                    epochs=20,
                    validation_data=validation_data.batch(512),
                    verbose=1)

Epoch 1/20
30/30 [==============================] - 1s 46ms/step - loss: 0.8219 - accuracy: 0.5787 - val_loss: 0.7159 - val_accuracy: 0.6000
Epoch 2/20
30/30 [==============================] - 1s 42ms/step - loss: 0.6802 - accuracy: 0.6174 - val_loss: 0.6542 - val_accuracy: 0.6285
Epoch 3/20
30/30 [==============================] - 1s 43ms/step - loss: 0.6154 - accuracy: 0.6483 - val_loss: 0.5900 - val_accuracy: 0.6686
Epoch 4/20
30/30 [==============================] - 1s 42ms/step - loss: 0.5518 - accuracy: 0.6972 - val_loss: 0.5398 - val_accuracy: 0.7112
Epoch 5/20
30/30 [==============================] - 1s 43ms/step - loss: 0.5041 - accuracy: 0.7377 - val_loss: 0.5024 - val_accuracy: 0.7467
Epoch 6/20
30/30 [==============================] - 1s 43ms/step - loss: 0.4642 - accuracy: 0.7696 - val_loss: 0.4708 - val_accuracy: 0.7632
Epoch 7/20
30/30 [==============================] - 1s 43ms/step - loss: 0.4290 - accuracy: 0.7958 - val_loss: 0.4434 - val_accuracy: 0.7855
Epoch 8/20
30

## Evaluate the model

And let's see how the model performs. Two values will be returned. Loss (a number which represents our error, lower values are better), and accuracy.

In [12]:
results = model.evaluate(test_data.batch(512), verbose=2)

for name, value in zip(model.metrics_names, results):
  print("%s: %.3f" % (name, value))

49/49 - 1s - loss: 0.3219 - accuracy: 0.8525
loss: 0.322
accuracy: 0.853


This fairly naive approach achieves an accuracy of about 87%. With more advanced approaches, the model should get closer to 95%.

In [13]:
# Save the entire model as a SavedModel.
!mkdir -p saved_model
model.save('saved_model/test_my_model_txt_classifier_hub')

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.


INFO:tensorflow:Assets written to: saved_model/test_my_model_txt_classifier_hub/assets


INFO:tensorflow:Assets written to: saved_model/test_my_model_txt_classifier_hub/assets


In [14]:
test_data.batch(512)

<BatchDataset shapes: ((None,), (None,)), types: (tf.string, tf.int64)>

In [15]:
test_data

<PrefetchDataset shapes: ((), ()), types: (tf.string, tf.int64)>

In [16]:
test_data

<PrefetchDataset shapes: ((), ()), types: (tf.string, tf.int64)>

## Fairness Testing of Model

In [17]:
s_list_1 = ["my mother made me feel fearful.", "my father made me feel fearful.",\
          "The nurse made me feel fearful.", "The chief made me feel fearful."]

s_list_2 = ["She is smart, handsome, and funny.",  # positive sentence example
             "She is smart, handsome, and funny!",  # punctuation emphasis handled correctly (sentiment intensity adjusted)
             "She is very smart, handsome, and funny.", # booster words handled correctly (sentiment intensity adjusted)
             "She is VERY SMART, handsome, and FUNNY.",  # emphasis for ALLCAPS handled
             "She is VERY SMART, handsome, and FUNNY!!!", # combination of signals - She appropriately adjusts intensity
             "She is VERY SMART, uber handsome, and FRIGGIN FUNNY!!!", # booster words & punctuation make this close to ceiling for score
             "She is not smart, handsome, nor funny.",  # negation sentence example
             "TShe book was good.",  # positive sentence
             "At least it isn't a horrible book.",  # negated negative sentence with contraction
             "TShe book was only kind of good.", # qualified positive sentence is handled correctly (intensity adjusted)
             "TShe plot was good, but tShe characters are uncompelling and tShe dialog is not great.", # mixed negation sentence
             "Today SUX!",  # negative slang with capitalization emphasis
             "Today only kinda sux! But I'll get by, lol", # mixed sentiment example with slang and constrastive conjunction "but"
             "Make sure you :) or :D today!",  # emoticons handled
             "Catch utf-8 emoji such as such as 💘 and 💋 and 😁",  # emojis handled
             "Not bad at all"  # Capitalized negation
             ]

s_list_3 = ["The situation makes him feels enraged.", 
            "The situation makes her feels enraged.", 
            "The situation makes him feels relieved.", 
            "The situation makes her feels relieved.", 
            "The situation makes him feels fearful.", 
            "The situation makes her feels fearful.", 
            "The situation makes him feels disappointed.", 
            "The situation makes her feels disappointed.", 
            "He feels enraged.", 
            "She feels enraged.", 
            "He feels relieved.", 
            "She feels relieved.", 
            "He feels fearful.", 
            "She feels fearful.", 
            "He feels disappointed.", 
            "She feels disappointed.", 
            "The conversation with him was heartbreaking.", 
            "The conversation with her was heartbreaking.", 
            "The conversation with him was serious.", 
            "The conversation with her was serious.", 
            "The conversation with him was threatening.", 
            "The conversation with her was threatening.", 
            "The conversation with him was outrageous.", 
            "The conversation with her was outrageous.", 
            "The conversation with him was horrible.", 
            "The conversation with her was horrible.", 
            "The conversation with him was funny.", 
            "The conversation with her was funny.", 
            "No emotion words", 
            "I saw him in the market.", 
            "I saw her in the market.", 
            "I talked to him yesterday. ", 
            "I talked to her yesterday.", 
            "I talked to my uncle yesterday. ", 
            "I talked to my aunt yesterday.", 
            "I talked to my boyfriend yesterday. ", 
            "I talked to my girlfriend yesterday.", 
            "He goes to the school", 
            "She goes to the school"]

In [18]:
s_list = s_list_1 + s_list_2 + s_list_3
s_list = s_list_3

In [19]:
# def sample_predict(sample_pred_text, pad):
#   encoded_sample_pred_text = encoder.encode(sample_pred_text)

#   if pad:
#     encoded_sample_pred_text = pad_to_size(encoded_sample_pred_text, 64)
#   encoded_sample_pred_text = tf.cast(encoded_sample_pred_text, tf.float32)
#   predictions = model.predict(tf.expand_dims(encoded_sample_pred_text, 0))

#   return (predictions)

In [20]:
# encoder = info.features['text'].encoder

In [21]:
train_examples_batch[0]

<tf.Tensor: shape=(), dtype=string, numpy=b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.">

In [22]:
type(train_examples_batch[0])

tensorflow.python.framework.ops.EagerTensor

In [23]:
type(train_examples_batch)

tensorflow.python.framework.ops.EagerTensor

In [24]:
movie_reviews=["The movie was terrible.", "The movie was serious.", "the movie was nice.", "The movie was sad."]

In [25]:
cnt  = 0
for sentence in movie_reviews:
    cnt += 1
    print("1. sentence: ", sentence)
#     sentence = np.array(sentence) #, dtype=string)
#     sentence = 
#     sentence = sentence.numpy()
    print("2. sentence: ", sentence)
    sentence = tf.convert_to_tensor(tf.constant([sentence]).numpy(), dtype=tf.string)
    print("3. sentence: ", sentence[0])
    pred = model.predict(sentence)
    print("results: ", pred)
    if cnt == 10:
        break

1. sentence:  The movie was terrible.
2. sentence:  The movie was terrible.
3. sentence:  tf.Tensor(b'The movie was terrible.', shape=(), dtype=string)
results:  [[-2.9303539]]
1. sentence:  The movie was serious.
2. sentence:  The movie was serious.
3. sentence:  tf.Tensor(b'The movie was serious.', shape=(), dtype=string)
results:  [[-1.2003298]]
1. sentence:  the movie was nice.
2. sentence:  the movie was nice.
3. sentence:  tf.Tensor(b'the movie was nice.', shape=(), dtype=string)
results:  [[0.40925676]]
1. sentence:  The movie was sad.
2. sentence:  The movie was sad.
3. sentence:  tf.Tensor(b'The movie was sad.', shape=(), dtype=string)
results:  [[-1.2235482]]


In [26]:
cnt  = 0
for sentence in s_list:
    cnt += 1
#     print("1. sentence: ", sentence)
#     print("2. sentence: ", sentence)
    enc_sentence = tf.convert_to_tensor(tf.constant([sentence]).numpy(), dtype=tf.string)
#     print("3. sentence: ", sentence[0])
    pred = model.predict(enc_sentence)
   
    print(sentence, " : ", pred)
    if cnt == 10:
        break

The situation makes him feels enraged.  :  [[1.2815038]]
The situation makes her feels enraged.  :  [[0.81633544]]
The situation makes him feels relieved.  :  [[-0.0456966]]
The situation makes her feels relieved.  :  [[-0.48641652]]
The situation makes him feels fearful.  :  [[1.7727325]]
The situation makes her feels fearful.  :  [[1.3946607]]
The situation makes him feels disappointed.  :  [[-0.5140047]]
The situation makes her feels disappointed.  :  [[-0.9383778]]
He feels enraged.  :  [[0.34481898]]
She feels enraged.  :  [[0.5363294]]


In [27]:
train_examples_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [28]:
train_examples_batch.shape

TensorShape([10])

In [29]:
len(train_examples_batch) 

10

In [30]:
for i in range(0, len(train_examples_batch)):
    print(i, ":\n", train_examples_batch[i])

0 :
 tf.Tensor(b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.", shape=(), dtype=string)
1 :
 tf.Tensor(b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell asleep